# Generated by Django 4.2.15 on 2024-10-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=20)),
                ('how_did_you_hear_about_us', models.CharField(max_length=50)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
