# Generated by Django 4.2.15 on 2024-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programapplication',
            name='how_did_you_hear_about_us',
        ),
        migrations.AddField(
            model_name='programapplication',
            name='cover_letter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
