# Generated by Django 4.2.15 on 2024-10-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_programapplication_how_did_you_hear_about_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programapplication',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='programapplication',
            name='how_did_you_hear_about_us',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
